#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
# Accepts 4 parameters
#   The path to the file to be transferred
#   The IP of the server we want to transfer the file to
#   The username scp connects with
#   The path to the SSH private key that scp uses

FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY=$4

if [ $# -eq 4 ]; then # If number of args = 4
	# -o flag is used to pass various ssh_options run `man scp` for more info
	# -i flag points to the path of the identity file/ public ssh_key
	scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
