#!/usr/bin/env bash
# Install nginx on your web-01
sudo apt update -y
sudo apt install nginx -y

# server
## Create default nginx folder
sudo mkdir -p /var/www/html

# Nginx should be listening on port 80
## by default nginx listens on 80, so skip

# When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World!
## Create default index.html file
sudo touch /var/www/html/index
sudo touch /var/www/html/index.html
sudo touch /var/www/html/index.htm
sudo touch /var/www/html/index.nginx-debian.html

## Change ownership of file and directories to current user to permit edits
sudo chown -R "$USER":"$USER" /var/www/html/index
sudo chown -R "$USER":"$USER" /var/www/html/index.html
sudo chown -R "$USER":"$USER" /var/www/html/index.htm
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html

## Append hello world to file
echo "Hello World!" >/var/www/html/index
echo "Hello World!" >/var/www/html/index.html
echo "Hello World!" >/var/www/html/index.htm
echo "Hello World!" >/var/www/html/index.nginx-debian.html

# Allow UFW firewall to receive xternal requests
sudo ufw allow 'Nginx HTTP'

# You can’t use systemctl for restarting nginx
sudo service nginx restart
