#!/usr/bin/env bash
# shellcheck disable=SC2154

# placeholder for nginx config

# Install nginx on your web-01
sudo apt update -y
sudo apt install nginx -y

# echo "$REDIRECT" >test_sed
# Double quote to prevent globbing and word splitting.
# echo "$REDIRECT" >/etc/nginx/sites-available/default

sed -i "/^\slocation \/.*/a\ \t \t if ($request_filename = ~/redirect_me){\n \t \t \t return 301 https://github.com/fashemma007\;\n \t}
" /etc/nginx/sites-available/default

# Allow UFW firewall to receive xternal requests
sudo ufw allow 'Nginx HTTP'

# You can’t use systemctl for restarting nginx
sudo service nginx restart
