#!/usr/bin/env bash
# placeholder for nginx config

REDIRECT="
server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;

	location /redirect_me {
			rewrite ^/redirect_me(.*) https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
			}
	}
	"
# Install nginx on your web-01
sudo apt update -y
sudo apt install nginx -y

# echo "$REDIRECT" >test_sed
# Double quote to prevent globbing and word splitting.
echo "$REDIRECT" >/etc/nginx/sites-available/default

# Allow UFW firewall to receive xternal requests
sudo ufw allow 'Nginx HTTP'

# You can’t use systemctl for restarting nginx
sudo service nginx restart
