#!/usr/bin/env bash
# Install nginx with custom 404 page that contains the string
# Ceci n'est pas une page.

# Install nginx
sudo apt update
sudo apt install -y nginx

REDIRECT="
server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;

	location ~/redirect_me {
				return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
				}

	error_page 404 /custom_404.html;
		location /custom_404.html {
				root /var/www/html;
				internal;
		}
	}
	"
# Add custom 404 error page to nginx confg
echo "$REDIRECT" >/etc/nginx/sites-available/default

# Create default nginx folder for pages
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www
echo 'Hello World!' >/var/www/html/index.html
# Create custom_404.html file
sudo touch /var/www/html/custom_404.html

# Change file ownership to current user to allow editing
sudo chown -R "$USER":"$USER" /var/www/html/custom_404.html

# Overwite file content
echo "Ceci n'est pas une page" >/var/www/html/custom_404.html

# Restart nginx server
sudo service nginx restart
