#!/usr/bin/env bash
# Installs, configures, and starts the server
sudo apt update -y
sudo apt install nginx -y

# server
## Create default nginx folder
sudo mkdir -p /var/www/html

## Create default index.html file
sudo touch /var/www/html/index.html
sudo touch /var/www/html/custom_404.html

## Change ownership of file and directories to current user to permit edits
sudo chown -R "$USER":"$USER" /var/www/html/index.html
sudo chown -R "$USER":"$USER" /var/www/html/custom_404.html

## Append hello world to file
echo "Hello World!" >/var/www/html/index.html

# Overwite file content
echo "Ceci n'est pas une page" >/var/www/html/custom_404.html

# Allow UFW firewall to receive xternal requests
sudo ufw allow 'Nginx HTTP'

REDIRECT="
server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;

	location / {
		# create custom header for the server
		add_header X-Served-By $(hostname -a);
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		return 301 https://github.com/fashemma007;
	}

	error_page 404 /custom_404.html;
		location /custom_404.html {
				root /var/www/html;
				internal;
		}
	}
	"
# Add custom 404 error page to nginx confg
echo "$REDIRECT" >/etc/nginx/sites-available/default

# Restart nginx server
sudo service nginx restart
