#!/usr/bin/env bash
echo "CREATE USER IF NOT EXISTS 'replica_user'@'%' IDENTIFIED BY 'replica'; 
		GRANT ALL PRIVILEGES ON *.* TO 'replica_user'@'%';
		GRANT SELECT ON mysql.user TO 'holberton_user'@'localhost';
" | mysql -uroot -p
