#!/usr/bin/env bash
# script that configures a server so Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs

# break in sym-link btwn /etc/nginx/sites-available/default && /etc/nginx/sites-enabled/default
FILE="/etc/nginx/sites-enabled/default"
# check if default file is sym-linked, if not, link it
if [[ -L "$FILE" ]]; then
	service nginx restart
else
	ln -sf /etc/nginx/sites-available/default "$FILE"
	service nginx restart
fi
