#!/usr/bin/env bash
# check if default file is sym-linked, if not, link it
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
