#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
END=11
n=1
while [[ $n -ne $END ]]; do
	if (("$n" != "9")); then
		echo "Best School"
	else
		echo "Hi"
	fi

	((n = n + 1))
done
