#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
END=20
n=1
while [[ $n -le $END ]]; do
	if (("$n" == "4")); then
		echo "$n"
		echo "bad luck from China"
	elif (("$n" == "9")); then
		echo "$n"
		echo "bad luck from Japan"
	elif (("$n" == "17")); then
		echo "$n"
		echo "bad luck from Italy"
	else
		echo "$n"
	fi

	((n = n + 1))
done
