#!/usr/bin/env bash
# [File tests operators](https://tldp.org/LDP/abs/html/fto.html)
file="school"

# -e checks if a file exists
if [ -e "$file" ]; then
	echo "$file file exists"
	# -s checks if a file size is not zero (0)
	if [ -s "$file" ]; then
		echo "$file file is not empty"
	else
		echo "$file file is empty"
	fi
	# -f checks if a file is  a regular file or not
	if [ -f "$file" ]; then
		echo "$file is a regular file"
	fi

else
	echo "$file file does not exist"
fi
